const express=require('express'); const session=require('express-session'); const bcrypt=require('bcryptjs');
const fs=require('fs'); const path=require('path'); const http=require('http'); const {Server}=require('socket.io'); const multer=require('multer');
const app=express(), server=http.createServer(app), io=new Server(server); const PORT=process.env.PORT||3000;
const DB=path.join(__dirname,'data','db.json'); const empty={users:[],services:[],portfolio:[],conversations:[],messages:[],communities:[],communityMembers:[],communityMessages:[],reviews:[]};
function load(){try{return {...empty,...JSON.parse(fs.readFileSync(DB,'utf8'))}}catch{return structuredClone(empty)}}
function save(d){fs.writeFileSync(DB,JSON.stringify(d,null,2))} function id(a){return a.length?Math.max(...a.map(x=>x.id))+1:1} function now(){return new Date().toISOString()}
const sess=session({secret:process.env.SESSION_SECRET||'hackathon-change-me',resave:false,saveUninitialized:false,cookie:{maxAge:86400000,httpOnly:true,sameSite:'lax'}}); app.use(sess); app.use(express.json()); app.use(express.urlencoded({extended:true})); app.use(express.static(path.join(__dirname,'public')));
const storage=multer.diskStorage({destination:(_,__,cb)=>cb(null,path.join(__dirname,'public','uploads')),filename:(_,f,cb)=>cb(null,Date.now()+'-'+f.originalname.replace(/[^a-zA-Z0-9._-]/g,'_'))}); const upload=multer({storage,limits:{fileSize:5*1024*1024}});
const auth=(req,res,next)=>req.session.userId?next():res.status(401).json({error:'Login required'}); const safeUser=u=>{if(!u)return null; let {password,...x}=u; return x};
app.post('/api/signup',async(req,res)=>{let d=load(); const {name,email,password,department='',semester=''}=req.body; if(!name||!email||!password)return res.status(400).json({error:'Name, email and password required'}); if(d.users.some(u=>u.email.toLowerCase()===email.toLowerCase()))return res.status(409).json({error:'Email already registered'}); const u={id:id(d.users),name,email:email.toLowerCase(),password:await bcrypt.hash(password,10),department,semester,bio:'',skills:[],createdAt:now()}; d.users.push(u);save(d);req.session.userId=u.id;res.json(safeUser(u))});
app.post('/api/login',async(req,res)=>{let d=load(); const u=d.users.find(x=>x.email===String(req.body.email||'').toLowerCase()); if(!u||!await bcrypt.compare(req.body.password||'',u.password))return res.status(401).json({error:'Invalid email or password'});req.session.userId=u.id;res.json(safeUser(u))});
app.post('/api/logout',(req,res)=>req.session.destroy(()=>res.json({ok:true}))); app.get('/api/me',auth,(req,res)=>{let d=load();res.json(safeUser(d.users.find(u=>u.id===req.session.userId)))});
app.put('/api/me',auth,(req,res)=>{let d=load(),u=d.users.find(x=>x.id===req.session.userId); ['name','department','semester','bio'].forEach(k=>{if(req.body[k]!==undefined)u[k]=req.body[k]}); if(req.body.skills!==undefined)u.skills=Array.isArray(req.body.skills)?req.body.skills:String(req.body.skills).split(',').map(s=>s.trim()).filter(Boolean);save(d);res.json(safeUser(u))});
app.get('/api/users',auth,(req,res)=>{let d=load(),q=String(req.query.q||'').toLowerCase();res.json(d.users.filter(u=>u.id!==req.session.userId&&(!q||[u.name,u.department,u.semester,...u.skills].join(' ').toLowerCase().includes(q))).map(u=>profile(d,u)))});
function profile(d,u){let rs=d.reviews.filter(r=>r.userId===u.id),rating=rs.length?rs.reduce((a,b)=>a+b.rating,0)/rs.length:null;return {...safeUser(u),rating:rating?+rating.toFixed(1):null,reviewCount:rs.length,services:d.services.filter(s=>s.userId===u.id),portfolio:d.portfolio.filter(p=>p.userId===u.id)}}
app.get('/api/users/:id',auth,(req,res)=>{let d=load(),u=d.users.find(x=>x.id===+req.params.id);if(!u)return res.status(404).json({error:'User not found'});res.json(profile(d,u))});
app.post('/api/portfolio',auth,(req,res)=>{let d=load(),p={id:id(d.portfolio),userId:req.session.userId,title:req.body.title,description:req.body.description||'',link:req.body.link||'',createdAt:now()};d.portfolio.push(p);save(d);res.json(p)});
app.delete('/api/portfolio/:id',auth,(req,res)=>{let d=load(),p=d.portfolio.find(x=>x.id===+req.params.id);if(!p)return res.status(404).json({error:'Not found'});if(p.userId!==req.session.userId)return res.status(403).json({error:'Forbidden'});d.portfolio=d.portfolio.filter(x=>x.id!==p.id);save(d);res.json({ok:true})});
app.get('/api/services',auth,(req,res)=>{let d=load(),q=String(req.query.q||'').toLowerCase(),dept=String(req.query.department||'').toLowerCase(); let rows=d.services.map(s=>({...s,user:safeUser(d.users.find(u=>u.id===s.userId))})).filter(s=>{let hay=[s.title,s.category,s.description,(s.skills||[]).join(' '),s.user?.name].join(' ').toLowerCase();return(!q||hay.includes(q))&&(!dept||s.user?.department.toLowerCase()===dept)}); if(q)rows=rows.map(s=>({...s,matchScore:Math.round((q.split(/\s+/).filter(w=>[s.title,s.description,(s.skills||[]).join(' ')].join(' ').toLowerCase().includes(w)).length/Math.max(1,q.split(/\s+/).length))*100)})).sort((a,b)=>b.matchScore-a.matchScore);res.json(rows)});
app.post('/api/services',auth,(req,res)=>{let d=load(),s={id:id(d.services),userId:req.session.userId,title:req.body.title,category:req.body.category||'',description:req.body.description||'',skills:Array.isArray(req.body.skills)?req.body.skills:String(req.body.skills||'').split(',').map(x=>x.trim()).filter(Boolean),availability:req.body.availability||'Active',createdAt:now()};if(!s.title)return res.status(400).json({error:'Title required'});d.services.push(s);save(d);res.json(s)});
app.put('/api/services/:id',auth,(req,res)=>{let d=load(),s=d.services.find(x=>x.id===+req.params.id);if(!s)return res.status(404).json({error:'Not found'});if(s.userId!==req.session.userId)return res.status(403).json({error:'You can edit only your services'});['title','category','description','availability'].forEach(k=>{if(req.body[k]!==undefined)s[k]=req.body[k]});if(req.body.skills!==undefined)s.skills=Array.isArray(req.body.skills)?req.body.skills:String(req.body.skills).split(',').map(x=>x.trim()).filter(Boolean);save(d);res.json(s)});
app.delete('/api/services/:id',auth,(req,res)=>{let d=load(),s=d.services.find(x=>x.id===+req.params.id);if(!s)return res.status(404).json({error:'Not found'});if(s.userId!==req.session.userId)return res.status(403).json({error:'You can delete only your services'});d.services=d.services.filter(x=>x.id!==s.id);save(d);res.json({ok:true})});
app.post('/api/reviews',auth,(req,res)=>{let d=load(),userId=+req.body.userId,rating=Math.max(1,Math.min(5,+req.body.rating));if(userId===req.session.userId)return res.status(400).json({error:'Cannot review yourself'});let r={id:id(d.reviews),userId,reviewerId:req.session.userId,rating,comment:req.body.comment||'',createdAt:now()};d.reviews.push(r);save(d);res.json(r)});
function convoView(d,c,uid){let otherId=c.members.find(x=>x!==uid),other=safeUser(d.users.find(u=>u.id===otherId)),msgs=d.messages.filter(m=>m.conversationId===c.id&&!m.deletedAt),last=msgs.at(-1),unread=msgs.filter(m=>m.senderId!==uid&&!m.readBy.includes(uid)).length;return {...c,other,last,unread}}
app.get('/api/conversations',auth,(req,res)=>{let d=load();res.json(d.conversations.filter(c=>c.members.includes(req.session.userId)).map(c=>convoView(d,c,req.session.userId)).sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt))))});
app.post('/api/conversations',auth,(req,res)=>{let d=load(),other=+req.body.userId;if(other===req.session.userId)return res.status(400).json({error:'Cannot message yourself'});let c=d.conversations.find(c=>c.members.length===2&&c.members.includes(req.session.userId)&&c.members.includes(other)&&(+c.serviceId||0)===(+req.body.serviceId||0));if(!c){c={id:id(d.conversations),members:[req.session.userId,other],serviceId:req.body.serviceId?+req.body.serviceId:null,createdAt:now(),updatedAt:now()};d.conversations.push(c);save(d)}res.json(convoView(d,c,req.session.userId))});
app.get('/api/conversations/:id/messages',auth,(req,res)=>{let d=load(),c=d.conversations.find(x=>x.id===+req.params.id&&x.members.includes(req.session.userId));if(!c)return res.status(403).json({error:'Forbidden'});d.messages.filter(m=>m.conversationId===c.id&&m.senderId!==req.session.userId&&!m.readBy.includes(req.session.userId)).forEach(m=>m.readBy.push(req.session.userId));save(d);res.json(d.messages.filter(m=>m.conversationId===c.id).map(m=>({...m,sender:safeUser(d.users.find(u=>u.id===m.senderId))}))) });
app.post('/api/conversations/:id/messages',auth,upload.single('attachment'),(req,res)=>{let d=load(),c=d.conversations.find(x=>x.id===+req.params.id&&x.members.includes(req.session.userId));if(!c)return res.status(403).json({error:'Forbidden'});let m={id:id(d.messages),conversationId:c.id,senderId:req.session.userId,body:req.body.body||'',replyTo:req.body.replyTo?+req.body.replyTo:null,attachment:req.file?'/uploads/'+req.file.filename:null,attachmentName:req.file?.originalname||null,readBy:[req.session.userId],createdAt:now(),editedAt:null,deletedAt:null};if(!m.body&&!m.attachment)return res.status(400).json({error:'Message or attachment required'});d.messages.push(m);c.updatedAt=now();save(d);io.to('c'+c.id).emit('message:new',m);res.json(m)});
app.put('/api/messages/:id',auth,(req,res)=>{let d=load(),m=d.messages.find(x=>x.id===+req.params.id);if(!m)return res.status(404).json({error:'Not found'});if(m.senderId!==req.session.userId)return res.status(403).json({error:'Forbidden'});m.body=req.body.body??m.body;m.editedAt=now();save(d);io.to('c'+m.conversationId).emit('message:updated',m);res.json(m)});
app.delete('/api/messages/:id',auth,(req,res)=>{let d=load(),m=d.messages.find(x=>x.id===+req.params.id);if(!m)return res.status(404).json({error:'Not found'});if(m.senderId!==req.session.userId)return res.status(403).json({error:'Forbidden'});m.body='';m.attachment=null;m.deletedAt=now();save(d);io.to('c'+m.conversationId).emit('message:deleted',{id:m.id});res.json({ok:true})});
app.get('/api/communities',auth,(req,res)=>{let d=load();res.json(d.communities.map(c=>({...c,members:d.communityMembers.filter(m=>m.communityId===c.id).length,joined:d.communityMembers.some(m=>m.communityId===c.id&&m.userId===req.session.userId)})))});
app.post('/api/communities',auth,(req,res)=>{let d=load(),c={id:id(d.communities),name:req.body.name,description:req.body.description||'',ownerId:req.session.userId,createdAt:now()};d.communities.push(c);d.communityMembers.push({id:id(d.communityMembers),communityId:c.id,userId:req.session.userId});save(d);res.json(c)});
app.post('/api/communities/:id/join',auth,(req,res)=>{let d=load(),cid=+req.params.id;if(!d.communityMembers.some(m=>m.communityId===cid&&m.userId===req.session.userId))d.communityMembers.push({id:id(d.communityMembers),communityId:cid,userId:req.session.userId});save(d);res.json({ok:true})});
app.get('/api/communities/:id/messages',auth,(req,res)=>{let d=load(),cid=+req.params.id;if(!d.communityMembers.some(m=>m.communityId===cid&&m.userId===req.session.userId))return res.status(403).json({error:'Join community first'});res.json(d.communityMessages.filter(m=>m.communityId===cid).map(m=>({...m,sender:safeUser(d.users.find(u=>u.id===m.senderId))}))) });
app.post('/api/communities/:id/messages',auth,(req,res)=>{let d=load(),cid=+req.params.id;if(!d.communityMembers.some(m=>m.communityId===cid&&m.userId===req.session.userId))return res.status(403).json({error:'Join community first'});let m={id:id(d.communityMessages),communityId:cid,senderId:req.session.userId,body:req.body.body,createdAt:now()};d.communityMessages.push(m);save(d);io.to('g'+cid).emit('community:new',m);res.json(m)});
io.engine.use(sess);io.on('connection',s=>{if(!s.request.session?.userId)return s.disconnect();s.on('join:conversation',cid=>s.join('c'+cid));s.on('join:community',cid=>s.join('g'+cid))});
server.listen(PORT,()=>console.log(`Caffeine n Connect running at http://localhost:${PORT}`));
